SELECT DISTINCT CATEGORY, SUBCATEGORY, TITLE, BESTSELLER, SUM(NO_OF_RATINGS)
FROM udemy_data
WHERE BESTSELLER ='YES'
AND NO_OF_RATINGS >= 1000
AND OVERALL_RATING >= 4.5
AND CATEGORY = 'DEVELOPMENT'
AND SUBCATEGORY = 'PROGRAMMING LANGUAGES'
GROUP BY CATEGORY, SUBCATEGORY, BESTSELLER, TITLE;
