SELECT 'JAVA' AS LANGUAGE_PROGRAM, SUM(NO_OF_RATINGS) AS VOTERS, SUBCATEGORY
FROM UDEMY_DATA
WHERE TITLE LIKE '*JAVA*'
AND BESTSELLER ='YES'
AND NO_OF_RATINGS >= 1000
AND OVERALL_RATING >= 4.5
AND CATEGORY = 'DEVELOPMENT'
AND SUBCATEGORY = 'PROGRAMMING LANGUAGES'
GROUP BY SUBCATEGORY

UNION

SELECT 'PYTHON' AS LANGUAGE_PROGRAM, SUM(NO_OF_RATINGS), SUBCATEGORY
FROM UDEMY_DATA
WHERE TITLE LIKE '*PYTHON*'
AND BESTSELLER ='YES'
AND NO_OF_RATINGS >= 1000
AND OVERALL_RATING >= 4.5
AND CATEGORY = 'DEVELOPMENT'
AND SUBCATEGORY = 'PROGRAMMING LANGUAGES'
GROUP BY SUBCATEGORY

UNION

SELECT 'REACT' AS LANGUAGE_PROGRAM, SUM(NO_OF_RATINGS), SUBCATEGORY
FROM UDEMY_DATA
WHERE TITLE LIKE '*REACT*'
AND BESTSELLER ='YES'
AND NO_OF_RATINGS >= 1000
AND OVERALL_RATING >= 4.5
AND CATEGORY = 'DEVELOPMENT'
AND SUBCATEGORY = 'PROGRAMMING LANGUAGES'
GROUP BY SUBCATEGORY

UNION

SELECT 'OTHER' AS LANGUAGE_PROGRAM, SUM(NO_OF_RATINGS), SUBCATEGORY
FROM UDEMY_DATA
WHERE TITLE NOT LIKE '*JAVA*' AND TITLE NOT LIKE '*PYTHON*' AND TITLE NOT LIKE '*REACT*' 
AND BESTSELLER ='YES'
AND NO_OF_RATINGS >= 1000
AND OVERALL_RATING >= 4.5
AND CATEGORY = 'DEVELOPMENT'
AND SUBCATEGORY = 'PROGRAMMING LANGUAGES'
GROUP BY SUBCATEGORY

UNION SELECT 'TOTAL' AS LANGUAGE_PROGRAM, SUM(NO_OF_RATINGS), SUBCATEGORY
FROM UDEMY_DATA
WHERE BESTSELLER ='YES'
AND NO_OF_RATINGS >= 1000
AND OVERALL_RATING >= 4.5
AND CATEGORY = 'DEVELOPMENT'
AND SUBCATEGORY = 'PROGRAMMING LANGUAGES'
GROUP BY SUBCATEGORY;
